# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://blog.hesiy.cn/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0
hasCJKLanguage = true
rssLimit = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  [permalinks.page]
    posts = '/posts/:slug/'
    copyright = '/copyright/'
  [permalinks.section]
    posts = '/posts/'
    copyright = '/copyright/'

[params]
    dateFormat = "2006 年 01 月 02 日"
  [params.artalk]
    server = 'https://fs_artalk.i45s.com'
    site = "FloatSheep's Blog"
