name: Funny Cat
on:
  - push
jobs:
  buildstatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name : Prepare NodePack
        run: |
          npm install cnpm --global

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Generate Hugo
        run: |
          hugo

      - name: Commit sitemap to Baidu
        run: |
          node ./scripts/after/sitemapCommit "./public/sitemap.xml" "${{ secrets.BAIDU_ZZT_URL }}"

      - name: Static Files Pre Set
        run: |
          node ./scripts/after/fileExtened

      - name: NPM Publish Pre Set
        run: |
          node ./scripts/after/pkgUpdate

      - name: NPM Publish
        run: |
          npm config set _authToken=${{ secrets.NPM_T }}
          cd ./public
          ls
          npm publish --access=public

      - name: Refresh cache
        run: |
          cnpm sync @floatsheep/fsl-blog